// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airsell.proto

package com.grpc.stub;

public final class Airsell {
  private Airsell() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SellRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.poc.SellRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string sellType = 2;</code>
     */
    java.lang.String getSellType();
    /**
     * <code>string sellType = 2;</code>
     */
    com.google.protobuf.ByteString
        getSellTypeBytes();

    /**
     * <code>bool isHosted = 3;</code>
     */
    boolean getIsHosted();

    /**
     * <code>bool isDcs = 4;</code>
     */
    boolean getIsDcs();
  }
  /**
   * Protobuf type {@code com.grpc.poc.SellRequest}
   */
  public  static final class SellRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.poc.SellRequest)
      SellRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SellRequest.newBuilder() to construct.
    private SellRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SellRequest() {
      id_ = 0;
      sellType_ = "";
      isHosted_ = false;
      isDcs_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SellRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sellType_ = s;
              break;
            }
            case 24: {

              isHosted_ = input.readBool();
              break;
            }
            case 32: {

              isDcs_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.stub.Airsell.SellRequest.class, com.grpc.stub.Airsell.SellRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SELLTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object sellType_;
    /**
     * <code>string sellType = 2;</code>
     */
    public java.lang.String getSellType() {
      java.lang.Object ref = sellType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sellType_ = s;
        return s;
      }
    }
    /**
     * <code>string sellType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSellTypeBytes() {
      java.lang.Object ref = sellType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sellType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISHOSTED_FIELD_NUMBER = 3;
    private boolean isHosted_;
    /**
     * <code>bool isHosted = 3;</code>
     */
    public boolean getIsHosted() {
      return isHosted_;
    }

    public static final int ISDCS_FIELD_NUMBER = 4;
    private boolean isDcs_;
    /**
     * <code>bool isDcs = 4;</code>
     */
    public boolean getIsDcs() {
      return isDcs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getSellTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sellType_);
      }
      if (isHosted_ != false) {
        output.writeBool(3, isHosted_);
      }
      if (isDcs_ != false) {
        output.writeBool(4, isDcs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getSellTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sellType_);
      }
      if (isHosted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isHosted_);
      }
      if (isDcs_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isDcs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.stub.Airsell.SellRequest)) {
        return super.equals(obj);
      }
      com.grpc.stub.Airsell.SellRequest other = (com.grpc.stub.Airsell.SellRequest) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getSellType()
          .equals(other.getSellType());
      result = result && (getIsHosted()
          == other.getIsHosted());
      result = result && (getIsDcs()
          == other.getIsDcs());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + SELLTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSellType().hashCode();
      hash = (37 * hash) + ISHOSTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsHosted());
      hash = (37 * hash) + ISDCS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsDcs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.stub.Airsell.SellRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.SellRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.SellRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.stub.Airsell.SellRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.poc.SellRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.poc.SellRequest)
        com.grpc.stub.Airsell.SellRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.stub.Airsell.SellRequest.class, com.grpc.stub.Airsell.SellRequest.Builder.class);
      }

      // Construct using com.grpc.stub.Airsell.SellRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        sellType_ = "";

        isHosted_ = false;

        isDcs_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellRequest_descriptor;
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.SellRequest getDefaultInstanceForType() {
        return com.grpc.stub.Airsell.SellRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.SellRequest build() {
        com.grpc.stub.Airsell.SellRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.SellRequest buildPartial() {
        com.grpc.stub.Airsell.SellRequest result = new com.grpc.stub.Airsell.SellRequest(this);
        result.id_ = id_;
        result.sellType_ = sellType_;
        result.isHosted_ = isHosted_;
        result.isDcs_ = isDcs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.stub.Airsell.SellRequest) {
          return mergeFrom((com.grpc.stub.Airsell.SellRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.stub.Airsell.SellRequest other) {
        if (other == com.grpc.stub.Airsell.SellRequest.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getSellType().isEmpty()) {
          sellType_ = other.sellType_;
          onChanged();
        }
        if (other.getIsHosted() != false) {
          setIsHosted(other.getIsHosted());
        }
        if (other.getIsDcs() != false) {
          setIsDcs(other.getIsDcs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.stub.Airsell.SellRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.stub.Airsell.SellRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sellType_ = "";
      /**
       * <code>string sellType = 2;</code>
       */
      public java.lang.String getSellType() {
        java.lang.Object ref = sellType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sellType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sellType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSellTypeBytes() {
        java.lang.Object ref = sellType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sellType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sellType = 2;</code>
       */
      public Builder setSellType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sellType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sellType = 2;</code>
       */
      public Builder clearSellType() {
        
        sellType_ = getDefaultInstance().getSellType();
        onChanged();
        return this;
      }
      /**
       * <code>string sellType = 2;</code>
       */
      public Builder setSellTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sellType_ = value;
        onChanged();
        return this;
      }

      private boolean isHosted_ ;
      /**
       * <code>bool isHosted = 3;</code>
       */
      public boolean getIsHosted() {
        return isHosted_;
      }
      /**
       * <code>bool isHosted = 3;</code>
       */
      public Builder setIsHosted(boolean value) {
        
        isHosted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isHosted = 3;</code>
       */
      public Builder clearIsHosted() {
        
        isHosted_ = false;
        onChanged();
        return this;
      }

      private boolean isDcs_ ;
      /**
       * <code>bool isDcs = 4;</code>
       */
      public boolean getIsDcs() {
        return isDcs_;
      }
      /**
       * <code>bool isDcs = 4;</code>
       */
      public Builder setIsDcs(boolean value) {
        
        isDcs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isDcs = 4;</code>
       */
      public Builder clearIsDcs() {
        
        isDcs_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.poc.SellRequest)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.poc.SellRequest)
    private static final com.grpc.stub.Airsell.SellRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.stub.Airsell.SellRequest();
    }

    public static com.grpc.stub.Airsell.SellRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SellRequest>
        PARSER = new com.google.protobuf.AbstractParser<SellRequest>() {
      @java.lang.Override
      public SellRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SellRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SellRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SellRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.stub.Airsell.SellRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SellResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.poc.SellResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responseStatus = 1;</code>
     */
    java.lang.String getResponseStatus();
    /**
     * <code>string responseStatus = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseStatusBytes();

    /**
     * <code>int32 sellStatus = 2;</code>
     */
    int getSellStatus();

    /**
     * <code>string isHostedCarrier = 3;</code>
     */
    java.lang.String getIsHostedCarrier();
    /**
     * <code>string isHostedCarrier = 3;</code>
     */
    com.google.protobuf.ByteString
        getIsHostedCarrierBytes();

    /**
     * <code>string isDcs = 4;</code>
     */
    java.lang.String getIsDcs();
    /**
     * <code>string isDcs = 4;</code>
     */
    com.google.protobuf.ByteString
        getIsDcsBytes();

    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    java.util.List<com.grpc.stub.Airsell.SellRequest> 
        getStreamDataList();
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    com.grpc.stub.Airsell.SellRequest getStreamData(int index);
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    int getStreamDataCount();
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    java.util.List<? extends com.grpc.stub.Airsell.SellRequestOrBuilder> 
        getStreamDataOrBuilderList();
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    com.grpc.stub.Airsell.SellRequestOrBuilder getStreamDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.grpc.poc.SellResponse}
   */
  public  static final class SellResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.poc.SellResponse)
      SellResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SellResponse.newBuilder() to construct.
    private SellResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SellResponse() {
      responseStatus_ = "";
      sellStatus_ = 0;
      isHostedCarrier_ = "";
      isDcs_ = "";
      streamData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SellResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseStatus_ = s;
              break;
            }
            case 16: {

              sellStatus_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              isHostedCarrier_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              isDcs_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                streamData_ = new java.util.ArrayList<com.grpc.stub.Airsell.SellRequest>();
                mutable_bitField0_ |= 0x00000010;
              }
              streamData_.add(
                  input.readMessage(com.grpc.stub.Airsell.SellRequest.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          streamData_ = java.util.Collections.unmodifiableList(streamData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.stub.Airsell.SellResponse.class, com.grpc.stub.Airsell.SellResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESPONSESTATUS_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseStatus_;
    /**
     * <code>string responseStatus = 1;</code>
     */
    public java.lang.String getResponseStatus() {
      java.lang.Object ref = responseStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string responseStatus = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseStatusBytes() {
      java.lang.Object ref = responseStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELLSTATUS_FIELD_NUMBER = 2;
    private int sellStatus_;
    /**
     * <code>int32 sellStatus = 2;</code>
     */
    public int getSellStatus() {
      return sellStatus_;
    }

    public static final int ISHOSTEDCARRIER_FIELD_NUMBER = 3;
    private volatile java.lang.Object isHostedCarrier_;
    /**
     * <code>string isHostedCarrier = 3;</code>
     */
    public java.lang.String getIsHostedCarrier() {
      java.lang.Object ref = isHostedCarrier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isHostedCarrier_ = s;
        return s;
      }
    }
    /**
     * <code>string isHostedCarrier = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIsHostedCarrierBytes() {
      java.lang.Object ref = isHostedCarrier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isHostedCarrier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISDCS_FIELD_NUMBER = 4;
    private volatile java.lang.Object isDcs_;
    /**
     * <code>string isDcs = 4;</code>
     */
    public java.lang.String getIsDcs() {
      java.lang.Object ref = isDcs_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isDcs_ = s;
        return s;
      }
    }
    /**
     * <code>string isDcs = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIsDcsBytes() {
      java.lang.Object ref = isDcs_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isDcs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STREAMDATA_FIELD_NUMBER = 5;
    private java.util.List<com.grpc.stub.Airsell.SellRequest> streamData_;
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    public java.util.List<com.grpc.stub.Airsell.SellRequest> getStreamDataList() {
      return streamData_;
    }
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    public java.util.List<? extends com.grpc.stub.Airsell.SellRequestOrBuilder> 
        getStreamDataOrBuilderList() {
      return streamData_;
    }
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    public int getStreamDataCount() {
      return streamData_.size();
    }
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    public com.grpc.stub.Airsell.SellRequest getStreamData(int index) {
      return streamData_.get(index);
    }
    /**
     * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
     */
    public com.grpc.stub.Airsell.SellRequestOrBuilder getStreamDataOrBuilder(
        int index) {
      return streamData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseStatus_);
      }
      if (sellStatus_ != 0) {
        output.writeInt32(2, sellStatus_);
      }
      if (!getIsHostedCarrierBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, isHostedCarrier_);
      }
      if (!getIsDcsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, isDcs_);
      }
      for (int i = 0; i < streamData_.size(); i++) {
        output.writeMessage(5, streamData_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseStatus_);
      }
      if (sellStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sellStatus_);
      }
      if (!getIsHostedCarrierBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, isHostedCarrier_);
      }
      if (!getIsDcsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, isDcs_);
      }
      for (int i = 0; i < streamData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, streamData_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.stub.Airsell.SellResponse)) {
        return super.equals(obj);
      }
      com.grpc.stub.Airsell.SellResponse other = (com.grpc.stub.Airsell.SellResponse) obj;

      boolean result = true;
      result = result && getResponseStatus()
          .equals(other.getResponseStatus());
      result = result && (getSellStatus()
          == other.getSellStatus());
      result = result && getIsHostedCarrier()
          .equals(other.getIsHostedCarrier());
      result = result && getIsDcs()
          .equals(other.getIsDcs());
      result = result && getStreamDataList()
          .equals(other.getStreamDataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSESTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getResponseStatus().hashCode();
      hash = (37 * hash) + SELLSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getSellStatus();
      hash = (37 * hash) + ISHOSTEDCARRIER_FIELD_NUMBER;
      hash = (53 * hash) + getIsHostedCarrier().hashCode();
      hash = (37 * hash) + ISDCS_FIELD_NUMBER;
      hash = (53 * hash) + getIsDcs().hashCode();
      if (getStreamDataCount() > 0) {
        hash = (37 * hash) + STREAMDATA_FIELD_NUMBER;
        hash = (53 * hash) + getStreamDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.stub.Airsell.SellResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.SellResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.SellResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.stub.Airsell.SellResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.poc.SellResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.poc.SellResponse)
        com.grpc.stub.Airsell.SellResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.stub.Airsell.SellResponse.class, com.grpc.stub.Airsell.SellResponse.Builder.class);
      }

      // Construct using com.grpc.stub.Airsell.SellResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStreamDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseStatus_ = "";

        sellStatus_ = 0;

        isHostedCarrier_ = "";

        isDcs_ = "";

        if (streamDataBuilder_ == null) {
          streamData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          streamDataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_SellResponse_descriptor;
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.SellResponse getDefaultInstanceForType() {
        return com.grpc.stub.Airsell.SellResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.SellResponse build() {
        com.grpc.stub.Airsell.SellResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.SellResponse buildPartial() {
        com.grpc.stub.Airsell.SellResponse result = new com.grpc.stub.Airsell.SellResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.responseStatus_ = responseStatus_;
        result.sellStatus_ = sellStatus_;
        result.isHostedCarrier_ = isHostedCarrier_;
        result.isDcs_ = isDcs_;
        if (streamDataBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            streamData_ = java.util.Collections.unmodifiableList(streamData_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.streamData_ = streamData_;
        } else {
          result.streamData_ = streamDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.stub.Airsell.SellResponse) {
          return mergeFrom((com.grpc.stub.Airsell.SellResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.stub.Airsell.SellResponse other) {
        if (other == com.grpc.stub.Airsell.SellResponse.getDefaultInstance()) return this;
        if (!other.getResponseStatus().isEmpty()) {
          responseStatus_ = other.responseStatus_;
          onChanged();
        }
        if (other.getSellStatus() != 0) {
          setSellStatus(other.getSellStatus());
        }
        if (!other.getIsHostedCarrier().isEmpty()) {
          isHostedCarrier_ = other.isHostedCarrier_;
          onChanged();
        }
        if (!other.getIsDcs().isEmpty()) {
          isDcs_ = other.isDcs_;
          onChanged();
        }
        if (streamDataBuilder_ == null) {
          if (!other.streamData_.isEmpty()) {
            if (streamData_.isEmpty()) {
              streamData_ = other.streamData_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureStreamDataIsMutable();
              streamData_.addAll(other.streamData_);
            }
            onChanged();
          }
        } else {
          if (!other.streamData_.isEmpty()) {
            if (streamDataBuilder_.isEmpty()) {
              streamDataBuilder_.dispose();
              streamDataBuilder_ = null;
              streamData_ = other.streamData_;
              bitField0_ = (bitField0_ & ~0x00000010);
              streamDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStreamDataFieldBuilder() : null;
            } else {
              streamDataBuilder_.addAllMessages(other.streamData_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.stub.Airsell.SellResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.stub.Airsell.SellResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object responseStatus_ = "";
      /**
       * <code>string responseStatus = 1;</code>
       */
      public java.lang.String getResponseStatus() {
        java.lang.Object ref = responseStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseStatus = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseStatusBytes() {
        java.lang.Object ref = responseStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseStatus = 1;</code>
       */
      public Builder setResponseStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseStatus = 1;</code>
       */
      public Builder clearResponseStatus() {
        
        responseStatus_ = getDefaultInstance().getResponseStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string responseStatus = 1;</code>
       */
      public Builder setResponseStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseStatus_ = value;
        onChanged();
        return this;
      }

      private int sellStatus_ ;
      /**
       * <code>int32 sellStatus = 2;</code>
       */
      public int getSellStatus() {
        return sellStatus_;
      }
      /**
       * <code>int32 sellStatus = 2;</code>
       */
      public Builder setSellStatus(int value) {
        
        sellStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sellStatus = 2;</code>
       */
      public Builder clearSellStatus() {
        
        sellStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object isHostedCarrier_ = "";
      /**
       * <code>string isHostedCarrier = 3;</code>
       */
      public java.lang.String getIsHostedCarrier() {
        java.lang.Object ref = isHostedCarrier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isHostedCarrier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isHostedCarrier = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIsHostedCarrierBytes() {
        java.lang.Object ref = isHostedCarrier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isHostedCarrier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isHostedCarrier = 3;</code>
       */
      public Builder setIsHostedCarrier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isHostedCarrier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string isHostedCarrier = 3;</code>
       */
      public Builder clearIsHostedCarrier() {
        
        isHostedCarrier_ = getDefaultInstance().getIsHostedCarrier();
        onChanged();
        return this;
      }
      /**
       * <code>string isHostedCarrier = 3;</code>
       */
      public Builder setIsHostedCarrierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isHostedCarrier_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object isDcs_ = "";
      /**
       * <code>string isDcs = 4;</code>
       */
      public java.lang.String getIsDcs() {
        java.lang.Object ref = isDcs_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isDcs_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isDcs = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIsDcsBytes() {
        java.lang.Object ref = isDcs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isDcs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isDcs = 4;</code>
       */
      public Builder setIsDcs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isDcs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string isDcs = 4;</code>
       */
      public Builder clearIsDcs() {
        
        isDcs_ = getDefaultInstance().getIsDcs();
        onChanged();
        return this;
      }
      /**
       * <code>string isDcs = 4;</code>
       */
      public Builder setIsDcsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isDcs_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.grpc.stub.Airsell.SellRequest> streamData_ =
        java.util.Collections.emptyList();
      private void ensureStreamDataIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          streamData_ = new java.util.ArrayList<com.grpc.stub.Airsell.SellRequest>(streamData_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpc.stub.Airsell.SellRequest, com.grpc.stub.Airsell.SellRequest.Builder, com.grpc.stub.Airsell.SellRequestOrBuilder> streamDataBuilder_;

      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public java.util.List<com.grpc.stub.Airsell.SellRequest> getStreamDataList() {
        if (streamDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(streamData_);
        } else {
          return streamDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public int getStreamDataCount() {
        if (streamDataBuilder_ == null) {
          return streamData_.size();
        } else {
          return streamDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public com.grpc.stub.Airsell.SellRequest getStreamData(int index) {
        if (streamDataBuilder_ == null) {
          return streamData_.get(index);
        } else {
          return streamDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder setStreamData(
          int index, com.grpc.stub.Airsell.SellRequest value) {
        if (streamDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStreamDataIsMutable();
          streamData_.set(index, value);
          onChanged();
        } else {
          streamDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder setStreamData(
          int index, com.grpc.stub.Airsell.SellRequest.Builder builderForValue) {
        if (streamDataBuilder_ == null) {
          ensureStreamDataIsMutable();
          streamData_.set(index, builderForValue.build());
          onChanged();
        } else {
          streamDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder addStreamData(com.grpc.stub.Airsell.SellRequest value) {
        if (streamDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStreamDataIsMutable();
          streamData_.add(value);
          onChanged();
        } else {
          streamDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder addStreamData(
          int index, com.grpc.stub.Airsell.SellRequest value) {
        if (streamDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStreamDataIsMutable();
          streamData_.add(index, value);
          onChanged();
        } else {
          streamDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder addStreamData(
          com.grpc.stub.Airsell.SellRequest.Builder builderForValue) {
        if (streamDataBuilder_ == null) {
          ensureStreamDataIsMutable();
          streamData_.add(builderForValue.build());
          onChanged();
        } else {
          streamDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder addStreamData(
          int index, com.grpc.stub.Airsell.SellRequest.Builder builderForValue) {
        if (streamDataBuilder_ == null) {
          ensureStreamDataIsMutable();
          streamData_.add(index, builderForValue.build());
          onChanged();
        } else {
          streamDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder addAllStreamData(
          java.lang.Iterable<? extends com.grpc.stub.Airsell.SellRequest> values) {
        if (streamDataBuilder_ == null) {
          ensureStreamDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, streamData_);
          onChanged();
        } else {
          streamDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder clearStreamData() {
        if (streamDataBuilder_ == null) {
          streamData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          streamDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public Builder removeStreamData(int index) {
        if (streamDataBuilder_ == null) {
          ensureStreamDataIsMutable();
          streamData_.remove(index);
          onChanged();
        } else {
          streamDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public com.grpc.stub.Airsell.SellRequest.Builder getStreamDataBuilder(
          int index) {
        return getStreamDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public com.grpc.stub.Airsell.SellRequestOrBuilder getStreamDataOrBuilder(
          int index) {
        if (streamDataBuilder_ == null) {
          return streamData_.get(index);  } else {
          return streamDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public java.util.List<? extends com.grpc.stub.Airsell.SellRequestOrBuilder> 
           getStreamDataOrBuilderList() {
        if (streamDataBuilder_ != null) {
          return streamDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(streamData_);
        }
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public com.grpc.stub.Airsell.SellRequest.Builder addStreamDataBuilder() {
        return getStreamDataFieldBuilder().addBuilder(
            com.grpc.stub.Airsell.SellRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public com.grpc.stub.Airsell.SellRequest.Builder addStreamDataBuilder(
          int index) {
        return getStreamDataFieldBuilder().addBuilder(
            index, com.grpc.stub.Airsell.SellRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .com.grpc.poc.SellRequest streamData = 5;</code>
       */
      public java.util.List<com.grpc.stub.Airsell.SellRequest.Builder> 
           getStreamDataBuilderList() {
        return getStreamDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpc.stub.Airsell.SellRequest, com.grpc.stub.Airsell.SellRequest.Builder, com.grpc.stub.Airsell.SellRequestOrBuilder> 
          getStreamDataFieldBuilder() {
        if (streamDataBuilder_ == null) {
          streamDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.grpc.stub.Airsell.SellRequest, com.grpc.stub.Airsell.SellRequest.Builder, com.grpc.stub.Airsell.SellRequestOrBuilder>(
                  streamData_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          streamData_ = null;
        }
        return streamDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.poc.SellResponse)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.poc.SellResponse)
    private static final com.grpc.stub.Airsell.SellResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.stub.Airsell.SellResponse();
    }

    public static com.grpc.stub.Airsell.SellResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SellResponse>
        PARSER = new com.google.protobuf.AbstractParser<SellResponse>() {
      @java.lang.Override
      public SellResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SellResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SellResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SellResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.stub.Airsell.SellResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpc.poc.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.grpc.poc.Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpc.poc.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.stub.Airsell.internal_static_com_grpc_poc_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.stub.Airsell.internal_static_com_grpc_poc_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.stub.Airsell.Empty.class, com.grpc.stub.Airsell.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.stub.Airsell.Empty)) {
        return super.equals(obj);
      }
      com.grpc.stub.Airsell.Empty other = (com.grpc.stub.Airsell.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.stub.Airsell.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.stub.Airsell.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.stub.Airsell.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpc.poc.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpc.poc.Empty)
        com.grpc.stub.Airsell.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.stub.Airsell.Empty.class, com.grpc.stub.Airsell.Empty.Builder.class);
      }

      // Construct using com.grpc.stub.Airsell.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.stub.Airsell.internal_static_com_grpc_poc_Empty_descriptor;
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.Empty getDefaultInstanceForType() {
        return com.grpc.stub.Airsell.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.Empty build() {
        com.grpc.stub.Airsell.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.stub.Airsell.Empty buildPartial() {
        com.grpc.stub.Airsell.Empty result = new com.grpc.stub.Airsell.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.stub.Airsell.Empty) {
          return mergeFrom((com.grpc.stub.Airsell.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.stub.Airsell.Empty other) {
        if (other == com.grpc.stub.Airsell.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.stub.Airsell.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.stub.Airsell.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpc.poc.Empty)
    }

    // @@protoc_insertion_point(class_scope:com.grpc.poc.Empty)
    private static final com.grpc.stub.Airsell.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.stub.Airsell.Empty();
    }

    public static com.grpc.stub.Airsell.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.stub.Airsell.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_poc_SellRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_poc_SellRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_poc_SellResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_poc_SellResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_poc_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpc_poc_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rairsell.proto\022\014com.grpc.poc\"L\n\013SellReq" +
      "uest\022\n\n\002id\030\001 \001(\005\022\020\n\010sellType\030\002 \001(\t\022\020\n\010is" +
      "Hosted\030\003 \001(\010\022\r\n\005isDcs\030\004 \001(\010\"\221\001\n\014SellResp" +
      "onse\022\026\n\016responseStatus\030\001 \001(\t\022\022\n\nsellStat" +
      "us\030\002 \001(\005\022\027\n\017isHostedCarrier\030\003 \001(\t\022\r\n\005isD" +
      "cs\030\004 \001(\t\022-\n\nstreamData\030\005 \003(\0132\031.com.grpc." +
      "poc.SellRequest\"\007\n\005Empty2\315\001\n\004Sell\022C\n\ncre" +
      "ateSell\022\031.com.grpc.poc.SellRequest\032\032.com" +
      ".grpc.poc.SellResponse\022C\n\nupdateSell\022\031.c" +
      "om.grpc.poc.SellRequest\032\032.com.grpc.poc.S" +
      "ellResponse\022;\n\010getSells\022\023.com.grpc.poc.E" +
      "mpty\032\032.com.grpc.poc.SellResponseB\017\n\rcom." +
      "grpc.stubb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_grpc_poc_SellRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_poc_SellRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_poc_SellRequest_descriptor,
        new java.lang.String[] { "Id", "SellType", "IsHosted", "IsDcs", });
    internal_static_com_grpc_poc_SellResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_poc_SellResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_poc_SellResponse_descriptor,
        new java.lang.String[] { "ResponseStatus", "SellStatus", "IsHostedCarrier", "IsDcs", "StreamData", });
    internal_static_com_grpc_poc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpc_poc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpc_poc_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
